### ISSUE TITLE
missing metatag

### ISSUE THREAD

**Issue by darioaschero** [apeunit/neueux#25]
page title, description favicons, open graph meta ..

**Comment by dgtlntv** [comment]
Missing Metatag on homepage (neueux.com):
Image = neueux logo

Missing Metatags in App Page (eg. https://neueux.com/apps/app-1618409563523-zengo-wallet-hejeoxdps):
Image = Logo of App

Missing Metatags in Filters (eg. https://neueux.com/filter?userflows=urnsc8ap3):
Title = the name of the filter

**Comment by musayann** [comment]
@darioaschero  and @dgtlntv, do you want these to be added as `alt` attribute of the images
